// flow-typed signature: 4e4ed57659bfb64c8105c2776370e258
// flow-typed version: <<STUB>>/eslint-config-shakacode_v^13.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-shakacode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-shakacode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-shakacode/base' {
  declare module.exports: any;
}

declare module 'eslint-config-shakacode/rules/javascript' {
  declare module.exports: any;
}

declare module 'eslint-config-shakacode/rules/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-shakacode/base.js' {
  declare module.exports: $Exports<'eslint-config-shakacode/base'>;
}
declare module 'eslint-config-shakacode/index' {
  declare module.exports: $Exports<'eslint-config-shakacode'>;
}
declare module 'eslint-config-shakacode/index.js' {
  declare module.exports: $Exports<'eslint-config-shakacode'>;
}
declare module 'eslint-config-shakacode/rules/javascript.js' {
  declare module.exports: $Exports<'eslint-config-shakacode/rules/javascript'>;
}
declare module 'eslint-config-shakacode/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-shakacode/rules/react'>;
}
