// flow-typed signature: 6d45b59c0cb4d0ab431cd91afd8ddf59
// flow-typed version: <<STUB>>/jest-junit_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-junit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-junit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-junit/index' {
  declare module.exports: $Exports<'jest-junit'>;
}
declare module 'jest-junit/index.js' {
  declare module.exports: $Exports<'jest-junit'>;
}
