#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# Start mailcatcher
if lsof -Pi :1025 -sTCP:LISTEN -t >/dev/null ; then
  echo "==> mailcatcher is already running"
else
  mailcatcher
fi

# Start redis
if [ "$(redis-cli ping)" = "PONG" ]; then
  echo "Redis is running."
else
  echo "==> Starting Redis server"
  redis-server &
  echo "==> Redis server started"
fi

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes.
foreman start -f Procfile.dev
