default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: react_on_rails_pro_development

test:
  <<: *default
  database: react_on_rails_pro_test

production:
  <<: *default
  database: react_on_rails_pro_production