AllCops:
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
