AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'

Lint/AssignmentInCondition:
  Exclude:

Metrics/BlockLength:
  Exclude:
    - 'spec/rails_helper.rb'

Metrics/LineLength:
  Max: 100

Bundler/OrderedGems:
  Enabled: false