---
extends:
  - eslint-config-shakacode
  - plugin:flowtype/recommended

plugins:
  - flowtype

settings:
  import/resolver:
    webpack:
      config: webpack.config.babel.js

env:
  browser: true
  mocha: true
  jquery: true

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true

rules:
  # Candidates for Official ShakaCode StyleGuide

  # Not clear why
  # http://eslint.org/docs/rules/no-continue
  no-continue: 0

  # Not clear why
  # http://eslint.org/docs/rules/no-plusplus
  no-plusplus: 0

  # This breaks flow type imports and it's handled by `import/no-duplicates`
  # http://eslint.org/docs/rules/no-duplicate-imports
  no-duplicate-imports: 0

  # This thing never worked as expected - everytime for a new reason, now it doesn't work b/c of @flow
  # https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md
  react/sort-comp: 0

  # This rule conflicts w/ @flow as we must type all props,
  # even some of them are not used in component
  # https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md
  react/no-unused-prop-types: 0

  # Ignoring test deps
  # https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md
  import/no-extraneous-dependencies:
    - 2
    - devDependencies:
        - "**/*.spec.js"
