// flow-typed signature: df0fa7655c00fa13a57007dba0d4a94f
// flow-typed version: <<STUB>>/@kadira/storybook-addons_v^1.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook-addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook-addons/dist/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addons/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storybook-addons/dist/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addons/dist/index'>;
}
declare module '@kadira/storybook-addons/src/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addons/src/index'>;
}
